[pyprland]
plugins = [
  "scratchpads",
  "magnify",
]

[scratchpads.term]
animation = "fromTop"
command = "foot --title scratchpad-term tmuxinator start term-scratchpad"
class = "scratchpad-term"
size = "75% 60%"
margin = 10
pinned = true

[scratchpads.notes]
animation = "fromTop"
command = "foot --title scratchpad-notes tmuxinator notes-scratchpad"
class = "scratchpad-notes"
size = "75% 60%"
margin = 10
pinned = true
