#!/bin/sh

lang_1="us"
lang_2="ru,ua"
options="grp:menu_toggle,caps:escape"

if setxkbmap -query | grep -q $lang_1; then
    setxkbmap -option $options -layout $lang_2 -variant , ;
else
    setxkbmap  -option $options -layout $lang_1 -variant , ;
fi
