#!/bin/sh

# setxkbmap -option 'grp:caps_toggle' -layout ru,ua
layout_1="us"
layout_2="ru,ua"
layout_current=$(setxkbmap -query | grep "layout" | awk '{print $2}')

if [ $layout_current = $layout_2 ]; then
    setxkbmap -option 'grp:menu_toggle' -layout $layout_1
    echo $layout_1
else
    setxkbmap -layout $layout_2
    echo $layout_2
fi
